# Generated by Django 2.2.7 on 2019-12-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amazon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprod', models.CharField(max_length=100)),
                ('aprice', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='flipkart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fprod', models.CharField(max_length=100)),
                ('fprice', models.CharField(max_length=100)),
            ],
        ),
    ]
