# Generated by Django 2.2.7 on 2019-12-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='amfp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fprod', models.CharField(max_length=100)),
                ('fprice', models.CharField(max_length=100)),
                ('aprod', models.CharField(max_length=100)),
                ('aprice', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='amazon',
        ),
        migrations.DeleteModel(
            name='flipkart',
        ),
    ]
